### ISSUE TITLE
[Bug]: hpo-3sigma自动计算超参数，dataset_path为目录时报错

### ISSUE THREAD

**Issue by Yang-QW** [modelscope/data-juicer#190]
### Before Reporting 报告之前

- [X] I have pulled the latest code of main branch to run again and the bug still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

- [X] I have read the [README](https://github.com/alibaba/data-juicer/blob/main/README.md) carefully and no error occurred during the installation process. (Otherwise, we recommend that you can ask a question using the Question template) 我已经仔细阅读了 [README](https://github.com/alibaba/data-juicer/blob/main/README_ZH.md) 上的操作指引，并且在安装过程中没有错误发生。（否则，我们建议您使用Question模板向我们进行提问）

### Search before reporting 先搜索，再报告

- [X] I have searched the Data-Juicer [issues](https://github.com/alibaba/data-juicer/issues) and found no similar bugs. 我已经在 [issue列表](https://github.com/alibaba/data-juicer/issues) 中搜索但是没有发现类似的bug报告。

### OS 系统

Ubuntu

### Installation Method 安装方式

docker image

### Data-Juicer Version Data-Juicer版本

v0.1.3

### Python Version Python版本

3.8.18

### Describe the bug 描述这个bug

使用tools/hpo/execute_hpo_3sigma.py自动生成超参数时，如果dataset_path是一个文件夹，会报以下错误：
![image](https://github.com/alibaba/data-juicer/assets/61730282/852774b5-09c3-4c61-93a9-29cebb2c7aa0)
找到报错的地方：
![image](https://github.com/alibaba/data-juicer/assets/61730282/d36d20b7-2abd-4216-81d6-11e6721ede00)
这里判断文件路径是否有误？这样只能支持传入一个jsonl文件或jsonl.zst文件。能否对这里进行一下修改？
另外，建议数据集加载也支持一下jsonl.gz格式的文件，从hf下载的数据集有很多是jsonl.gz格式的，我尝试修改了一下支持的后缀名，发现是可以加载的，希望在后续更新中能增加这个选项。

### To Reproduce 如何复现

cd tools/hpo
python  execute_hpo_3sigma.py --config configs/test_config.yaml --path_3sigma_recipe configs/result.yaml

### Configs 配置信息

dataset_path: '/large-storage/dataset/.../Test' # 数据集路径是一个文件目录，目录下全是jsonl文件

### Logs 报错日志

File "execute_hpo_3sigma.py", line 73, in <module>
    main()
    └ <function main at 0x7fafea0343a0>

  File "execute_hpo_3sigma.py", line 34, in main
    op_name_to_stats_key = StatsKeys.get_access_log(dj_cfg=cfg)
                           │         │                     └ Namespace(add_suffix=False, alphanumeric_filter=Namespace(image_key=None, max_ratio=9223372036854775807, min_ratio=0.25, text...
                           │         └ <function StatsKeysMeta.get_access_log at 0x7fafe8d6baf0>
                           └ <class 'data_juicer.utils.constant.StatsKeys'>

  File "/data-juicer/data_juicer/utils/constant.py", line 93, in get_access_log
    raise NotImplementedError(

NotImplementedError: For now, the dummy data is supported for only jsonl type. Please check your config as /large-storage/dataset/.../Test is either not existed or in jsonl type.

**Comment by yxdyc** [comment]
非常感谢对该工具的使用和体验反馈。 支持文件夹及jsonl.gz格式确实是合理的使用需求，我们会尽快更新来支持相关特性；如果你已经有实现好的版本的话，也欢迎作为contributor直接提PR :)
