### ISSUE TITLE
3sigma在alphanumeric_filter中是如何计算的？

### ISSUE THREAD

**Issue by echo-valor** [modelscope/data-juicer#218]
### Before Asking 在提问之前

- [X] I have read the [README](https://github.com/alibaba/data-juicer/blob/main/README.md) carefully. 我已经仔细阅读了 [README](https://github.com/alibaba/data-juicer/blob/main/README_ZH.md) 上的操作指引。

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking 先搜索，再提问

- [X] I have searched the Data-Juicer [issues](https://github.com/alibaba/data-juicer/issues) and found no similar questions. 我已经在 [issue列表](https://github.com/alibaba/data-juicer/issues) 中搜索但是没有发现类似的问题。

### Question

Question: 都是英文的数据，请问下面的min_ratio、max_ratio值是怎么计算出来的？是与数量有关吗？为什么下面两种菜谱要设置完全不同范围的参数呢？

在菜谱redpajama-pile-stackexchange-refine.yaml中，给出的参数为：
- alphanumeric_filter:
          tokenization: false
          min_ratio: **0.35**  # <3sigma
          max_ratio: **0.943**  # 3sigma

在菜谱redpajama-wiki-refine.yaml中，给出的参数为：
- alphanumeric_filter:
          tokenization: false
          min_ratio: **0.6**  # <3sigma (0.735)
          max_ratio: **0.884**  # 3sigma

**Comment by yxdyc** [comment]
We calculate these values based on 3-Sigma principles, see more details [here](https://github.com/alibaba/data-juicer/tree/main/tools/hpo#auto-hpo-based-on-3-sigma-principles)

**Comment by cnlinxi** [comment]
> We got these values based on 3-Sigma principles, see more details [here](https://github.com/alibaba/data-juicer/tree/main/tools/hpo#auto-hpo-based-on-3-sigma-principles)

@yxdyc 

Dear authors:

I want to find a set of hyper-parameters that works well for the specific data, so I follow [auto-hpo-based-on-3-sigma-principles](https://github.com/alibaba/data-juicer/tree/main/tools/hpo#auto-hpo-based-on-3-sigma-principles)：

```shell
python tools/hpo/execute_hpo_3sigma.py --config ${config_path} --path_k_sigma_recipe ${refine_config_path}
```

However, when I check the `${refine_config_path}` file, I find that the hyper-parameters in it are the same as the original `${config_path}`.

For example, the original `${config_path}` is [redpajama-code-refine.yaml](https://github.com/modelscope/data-juicer/blob/main/configs/data_juicer_recipes/github_code/redpajama-code-refine.yaml), and the `${refine_config_path}` is:

```xml
- alphanumeric_filter:
    accelerator: null
    audio_key: audios
    audio_special_token: <__dj__audio>
    cpu_required: null
    eoc_special_token: <|__dj__eoc|>
    gpu_required: null
    history_key: history
    image_bytes_key: image_bytes
    image_key: images
    image_special_token: <__dj__image>
    index_key: null
    instruction_key: instruction
    max_closed_interval: true
    max_ratio: 3
    mem_required: null
    min_closed_interval: true
    min_ratio: 1.5
    num_proc: 50
    prompt_key: prompt
    query_key: query
    response_key: response
    reversed_range: false
    skip_op_error: true
    stats_export_path: null
    system_key: system
    text_key: content
    tokenization: true
    turbo: false
    video_key: videos
    video_special_token: <__dj__video>
    work_dir: /home/data
```

The situation of other hyper-parameters is similar.

Is there something wrong?
