### ISSUE TITLE
Can not download the data quality classifier models. 

### ISSUE THREAD

**Issue by Chain123** [modelscope/data-juicer#266]
Can not open and download models from the given url at：https://dail-wlcb.oss-cn-wulanchabu.aliyuncs.com

# Got the following error message on a Browser(Chrome)
```html
<Error>
<Code>AccessDenied</Code> 
<Message>Anonymous user has no right to access this bucket.</Message>
<RequestId>65FACBBA2D4AB73334BE2FCF</RequestId>
<HostId>dail-wlcb.oss-cn-wulanchabu.aliyuncs.com</HostId>
<EC>0003-00000002</EC>
<RecommendDoc>https://api.aliyun.com/troubleshoot?q=0003-00000002</RecommendDoc>
</Error>
``` 

# And got a Timeout error when running the code: 

```shell
python predict.py --dataset_path redpajama-cc-2019-30/ --result_path version1/mid/redpajama-cc-2019-30 --model gpt3
``` 

File "~/conda-env/envs/data-juicer/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
    │ │       │   │             │   │         │   │     └ {'Host': 'dail-wlcb.oss-cn-wulanchabu.aliyuncs.com', 'User-Agent': 'Python-urllib/3.10', 'Connection': 'close'}
    │ │       │   │             │   │         │   └ <property object at 0x7f494fceeb10>
    │ │       │   │             │   │         └ <urllib.request.Request object at 0x7f4654d0a530>
    │ │       │   │             │   └ '/data_juicer/models/gpt3_quality_model.zip'
    │ │       │   │             └ <urllib.request.Request object at 0x7f4654d0a530>
    │ │       │   └ <function Request.get_method at 0x7f494fd01360>
    │ │       └ <urllib.request.Request object at 0x7f4654d0a530>
    │ └ <function HTTPConnection.request at 0x7f494fce3910>
    └ <http.client.HTTPSConnection object at 0x7f4654d0a8f0>

TimeoutError: [Errno 110] Connection timed out

**Comment by HYLcool** [comment]
Hi, @Chain123 

Thanks for your interest!

I ran the predict.py tool of the quality classifier on my machine just now and it did download the model successfully, so maybe something is wrong between your network and Aliyun OSS. The URL you tried is the root URL and getting the error message is kind of normal.

You can try to download the model manually from this URL: https://dail-wlcb.oss-cn-wulanchabu.aliyuncs.com/data_juicer/models/{model_name}_quality_model.zip by replacing `model_name` with one of `['gpt3', 'chinese', 'code']` and unzip it into the directory `~/.cache/data_juicer/models`.
