### ISSUE TITLE
alphanumeric_filter算子清洗疑问

### ISSUE THREAD

**Issue by echo-valor** [modelscope/data-juicer#267]
1. 在使用Data-Juicer处理网络的开源数据时，使用alphanumeric_filter算子来过滤掉非中文或者特殊字符较多的样本，参数设置如下：

> alphanumeric_filter:
      **tokenization**: false
      **min_ratio**: 0.0
      **max_ratio**: 0.9

但查看日志，发现类似该两条数据被过滤掉了：
![image](https://github.com/alibaba/data-juicer/assets/28260618/8237d345-6556-4dbe-8593-40fcd1eda6a3)

但这两条数据的非中文或者特殊字符比例均为大于0.9，为什么被过滤掉？很奇怪

Note: 很不错的数据处理流水线系统！

**Comment by echo-valor** [comment]
我这里设置的max_ratio=0.9 min_ratio=0.0：

- 直接来看，这两条样本的非中文或者特殊字符比例肯定没有到90%以上哇，求解答？

**Comment by zhijianma** [comment]
> 我这里设置的max_ratio=0.9 min_ratio=0.0：
> 
> * 直接来看，这两条样本的非中文或者特殊字符比例肯定没有到90%以上哇，求解答？

可以参考 #98  中的针对python 中对于字母的[定义](https://github.com/alibaba/data-juicer/issues/98#issuecomment-1825099008)
