### ISSUE TITLE
[Bug]: process on ray occur "TypeError: 'str' object cannot be interpreted as an integer"

### ISSUE THREAD

**Issue by laolv421** [modelscope/data-juicer#281]
### Before Reporting 报告之前

- [X] I have pulled the latest code of main branch to run again and the bug still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

- [X] I have read the [README](https://github.com/alibaba/data-juicer/blob/main/README.md) carefully and no error occurred during the installation process. (Otherwise, we recommend that you can ask a question using the Question template) 我已经仔细阅读了 [README](https://github.com/alibaba/data-juicer/blob/main/README_ZH.md) 上的操作指引，并且在安装过程中没有错误发生。（否则，我们建议您使用Question模板向我们进行提问）

### Search before reporting 先搜索，再报告

- [X] I have searched the Data-Juicer [issues](https://github.com/alibaba/data-juicer/issues) and found no similar bugs. 我已经在 [issue列表](https://github.com/alibaba/data-juicer/issues) 中搜索但是没有发现类似的bug报告。

### OS 系统

ubuntu

### Installation Method 安装方式

source

### Data-Juicer Version Data-Juicer版本

v0.2.0

### Python Version Python版本

3.8.18

### Describe the bug 描述这个bug

When run following cmd: python tools/process_data.py --config ./demos/process_on_ray/configs/demo.yaml, occur some type error, the whole traceback on the screen. 
ray version is 2.7.0

### To Reproduce 如何复现

python tools/process_data.py --config ./demos/process_on_ray/configs/demo.yaml

### Screenshots 截图

![1](https://github.com/modelscope/data-juicer/assets/14885612/dd421deb-4a8c-4a9c-be99-5a201b766bea)
![2](https://github.com/modelscope/data-juicer/assets/14885612/751640c2-cdc5-4d31-9b0e-78bd3ded0536)
![3](https://github.com/modelscope/data-juicer/assets/14885612/2c976f4f-353e-4032-9a5e-7f9bfb20a034)
![4](https://github.com/modelscope/data-juicer/assets/14885612/1b614711-bcba-4b0f-83aa-81313906c742)

**Comment by garyzhang99** [comment]
I was unable to reproduce this bug when running the command. Could you try running it again after executing pip install -v -e .\[sci\]?

**Comment by laolv421** [comment]
> I was unable to reproduce this bug when running the command. Could you try running it again after executing pip install -v -e .[sci]?

This error occured again after I executed `pip install -v -e .[sci]`. 
* ray version=2.7.0
* python version=3.8.18
* data juicer =0.2.0

![5](https://github.com/modelscope/data-juicer/assets/14885612/b0fd01c7-7c92-4beb-97d7-4f821f578184)
This error is weird, after I commented line 83, it will raise error from line 88.
![6](https://github.com/modelscope/data-juicer/assets/14885612/0a83de44-c01a-4de6-a83d-f5dd740527e5)

**Comment by garyzhang99** [comment]
> > I was unable to reproduce this bug when running the command. Could you try running it again after executing pip install -v -e .[sci]?
> 
> This error occured again after I executed `pip install -v -e .[sci]`.
> 
> * ray version=2.7.0
> * python version=3.8.18
> * data juicer =0.2.0
> 
> ![5](https://private-user-images.githubusercontent.com/14885612/317105350-b0fd01c7-7c92-4beb-97d7-4f821f578184.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MDk2NjgsIm5iZiI6MTcxMTUwOTM2OCwicGF0aCI6Ii8xNDg4NTYxMi8zMTcxMDUzNTAtYjBmZDAxYzctN2M5Mi00YmViLTk3ZDctNGY4MjFmNTc4MTg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDAzMTYwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkOThlNTdmMzJkZjI2YjA2MGMwOTVhNzM2NTExMGNkMDUyMWEwYmQxMmMxY2JmNjM2YWYxZDdlN2NjZmJkY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CFZmS4Nj_eZP5RSngOZpC-tFqWUmaHduqdhqJO20hyk) This error is weird, after I commented line 83, it will raise error from line 88. ![6](https://private-user-images.githubusercontent.com/14885612/317109958-0a83de44-c01a-4de6-a83d-f5dd740527e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MDk2NjgsIm5iZiI6MTcxMTUwOTM2OCwicGF0aCI6Ii8xNDg4NTYxMi8zMTcxMDk5NTgtMGE4M2RlNDQtYzAxYS00ZGU2LWE4M2QtZjVkZDc0MDUyN2U1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDAzMTYwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0MDhjMWM1OGQ4YTQ4ZTA4OThiZjNiMzZjZjdiZGRmMDU2NmZkZDlkNmViMTU5N2UwYWI4OTI4ZjJlYjUyODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uoKSNqvz7Ukh8hHvubhuEC0IYDSzlv-hJR3p6GIttPo)

When using Ray in a distributed setting, due to Ray's feature (Ray future), Ray does not compute directly at the corresponding line of code. Instead, the computation is performed when the result is called. After you commented out line 83, the computation that was originally performed at line 83 is executed at line 88, leading to an error at line 88, whereas the actual error should have occurred before line 83.

The error reporting mechanism of Ray makes it difficult to pinpoint the corresponding error. Could you try not using Ray first and run the corresponding code in a single-machine version to see if there are more complete error messages?

**Comment by laolv421** [comment]
> > > I was unable to reproduce this bug when running the command. Could you try running it again after executing pip install -v -e .[sci]?
> > 
> > 
> > This error occured again after I executed `pip install -v -e .[sci]`.
> > 
> > * ray version=2.7.0
> > * python version=3.8.18
> > * data juicer =0.2.0
> > 
> > ![5](https://private-user-images.githubusercontent.com/14885612/317105350-b0fd01c7-7c92-4beb-97d7-4f821f578184.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MDk2NjgsIm5iZiI6MTcxMTUwOTM2OCwicGF0aCI6Ii8xNDg4NTYxMi8zMTcxMDUzNTAtYjBmZDAxYzctN2M5Mi00YmViLTk3ZDctNGY4MjFmNTc4MTg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDAzMTYwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkOThlNTdmMzJkZjI2YjA2MGMwOTVhNzM2NTExMGNkMDUyMWEwYmQxMmMxY2JmNjM2YWYxZDdlN2NjZmJkY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CFZmS4Nj_eZP5RSngOZpC-tFqWUmaHduqdhqJO20hyk) This error is weird, after I commented line 83, it will raise error from line 88. ![6](https://private-user-images.githubusercontent.com/14885612/317109958-0a83de44-c01a-4de6-a83d-f5dd740527e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MDk2NjgsIm5iZiI6MTcxMTUwOTM2OCwicGF0aCI6Ii8xNDg4NTYxMi8zMTcxMDk5NTgtMGE4M2RlNDQtYzAxYS00ZGU2LWE4M2QtZjVkZDc0MDUyN2U1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDAzMTYwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0MDhjMWM1OGQ4YTQ4ZTA4OThiZjNiMzZjZjdiZGRmMDU2NmZkZDlkNmViMTU5N2UwYWI4OTI4ZjJlYjUyODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uoKSNqvz7Ukh8hHvubhuEC0IYDSzlv-hJR3p6GIttPo)
> 
> When using Ray in a distributed setting, due to Ray's feature (Ray future), Ray does not compute directly at the corresponding line of code. Instead, the computation is performed when the result is called. After you commented out line 83, the computation that was originally performed at line 83 is executed at line 88, leading to an error at line 88, whereas the actual error should have occurred before line 83.
> 
> The error reporting mechanism of Ray makes it difficult to pinpoint the corresponding error. Could you try not using Ray first and run the corresponding code in a single-machine version to see if there are more complete error messages?

Thanks for your advice. I have tested the code without Ray, and everything worked as expected, normally. I then double-checked the demo.yaml file, modified `ray_address: 'ray://localhost:10001'` to `ray_address: 'auto'` and ran the code.  Everything worked normally except for two operators with models, namely, `language_id_score_filter` and `perplexity_filter`. When I commented out these two operators, it worked fine. I conducted unit tests on both operators, and they both worked. But on the local ray, they were unable to find the model. 
```
# language_id_score_filter
  File "/home/lzj/project/open-source/data-juicer/data_juicer/ops/filter/language_id_score_filter.py", line 53, in compute_stats
    raise ValueError(err_msg)
ValueError: Model not loaded. Please retry later.
# perplexity_filter
  File "/home/lzj/project/open-source/data-juicer/data_juicer/ops/filter/perplexity_filter.py", line 71, in compute_stats
    logits += kenlm_model.score(line)
AttributeError: 'NoneType' object has no attribute 'score'

```

**Comment by garyzhang99** [comment]
Based solely on the provided description, we have not been able to reproduce the bug, nor can we pinpoint the specific issue. It appears it might be an environmental problem or an issue with the get_model and check_model functions. Could you provide more information?

Additionally, I would like to ask whether CUDA is enabled in your local environment and whether the corresponding Data-Juicer version is up to date.

**Comment by laolv421** [comment]
> Based solely on the provided description, we have not been able to reproduce the bug, nor can we pinpoint the specific issue. It appears it might be an environmental problem or an issue with the get_model and check_model functions. Could you provide more information?
> 
> Additionally, I would like to ask whether CUDA is enabled in your local environment and whether the corresponding Data-Juicer version is up to date.

* torch.cuda.is_available() = True
* data-juicer = v0.2.0
Here are the screenshots. I hope they are helpful for you.
![1](https://github.com/modelscope/data-juicer/assets/14885612/d17b0baa-f759-4c34-8dc0-86eebf4a7058)
![2](https://github.com/modelscope/data-juicer/assets/14885612/906e37b6-30a6-4276-b4f3-ddbb06500a44)
![3](https://github.com/modelscope/data-juicer/assets/14885612/fcf46390-2475-4521-8098-32910d181e93)
![4](https://github.com/modelscope/data-juicer/assets/14885612/aa53e575-2c54-4b61-ba27-967750e780b5)

**Comment by garyzhang99** [comment]
> > Based solely on the provided description, we have not been able to reproduce the bug, nor can we pinpoint the specific issue. It appears it might be an environmental problem or an issue with the get_model and check_model functions. Could you provide more information?
> > Additionally, I would like to ask whether CUDA is enabled in your local environment and whether the corresponding Data-Juicer version is up to date.
> 
> * torch.cuda.is_available() = True
> * data-juicer = v0.2.0
>   Here are the screenshots. I hope they are helpful for you.
>   ![1](https://private-user-images.githubusercontent.com/14885612/317249666-d17b0baa-f759-4c34-8dc0-86eebf4a7058.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1NDA0MTQsIm5iZiI6MTcxMTU0MDExNCwicGF0aCI6Ii8xNDg4NTYxMi8zMTcyNDk2NjYtZDE3YjBiYWEtZjc1OS00YzM0LThkYzAtODZlZWJmNGE3MDU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDExNDgzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2MzY1ZTRmZWUyMmU0NmU2MTk2ZDVmNzA2ZDIxZDcwYWJjOGIzYjNjYjE0ZmM3NjI0ZWMzMGU5NTUwMzAxMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-ufWB9jLmwx-5qD7sWxuUNRgyvrXqdabbBVpbPxz8B4)
>   ![2](https://private-user-images.githubusercontent.com/14885612/317249653-906e37b6-30a6-4276-b4f3-ddbb06500a44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1NDA0MTQsIm5iZiI6MTcxMTU0MDExNCwicGF0aCI6Ii8xNDg4NTYxMi8zMTcyNDk2NTMtOTA2ZTM3YjYtMzBhNi00Mjc2LWI0ZjMtZGRiYjA2NTAwYTQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDExNDgzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkOGFiYzFjNmE3NmEyODBmMTBiZWI2MTMwNjY2M2MwOTg0MmI4NGJmNDg0NmY5YjZiNmYwNWFjYWJmMjliYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S89Ro461Eo31ZXRmfklIcrSTqmyXaDAGiWbBNFttIQ0)
>   ![3](https://private-user-images.githubusercontent.com/14885612/317249641-fcf46390-2475-4521-8098-32910d181e93.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1NDA0MTQsIm5iZiI6MTcxMTU0MDExNCwicGF0aCI6Ii8xNDg4NTYxMi8zMTcyNDk2NDEtZmNmNDYzOTAtMjQ3NS00NTIxLTgwOTgtMzI5MTBkMTgxZTkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDExNDgzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1NDU5NjAwMDg0N2U0Nzk4YzUxOWE5MWM3MmI0YmM0ODIyZTA5MWMxM2YzYmNjMjczMWNkNDFkMDE3NTk5MzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yF7pRhwkfEQrQDzf_EjIVzdnseAj3xofsjjdrGjuAHY)
>   ![4](https://private-user-images.githubusercontent.com/14885612/317249628-aa53e575-2c54-4b61-ba27-967750e780b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1NDA0MTQsIm5iZiI6MTcxMTU0MDExNCwicGF0aCI6Ii8xNDg4NTYxMi8zMTcyNDk2MjgtYWE1M2U1NzUtMmM1NC00YjYxLWJhMjctOTY3NzUwZTc4MGI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDExNDgzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzN2E4NzhmOTkyODFlY2QzODJhNjI4NDllN2ZiYzA5MjZjYzQwMGJjNWIzODJjNTBkMWI3OGE1ZmRjZTYyNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M_B84npQZOxBaYAAWxBFFZsi5TqN3VcOJFUcQS1Cfv4)

It looks like the issue may be because you are using an older version of data-juicer, which previously did not have good support for CUDA in the Ray distributed version. You can try these two solutions separately：

- Pull the latest data-juicer code from the main branch on GitHub, then build from source (pip install -v -e .).
- Avoid using CUDA by setting the use_cuda related configurations to False in the code and modifying the CUDA environment variables accordingly.

It should be able to solve your problem.

**Comment by laolv421** [comment]
@garyzhang99 It worked, thanks a lot.
