### ISSUE TITLE
About Quality Classifier

### ISSUE THREAD

**Issue by koanho** [modelscope/data-juicer#321]
### Before Asking 在提问之前

- [X] I have read the [README](https://github.com/alibaba/data-juicer/blob/main/README.md) carefully. 我已经仔细阅读了 [README](https://github.com/alibaba/data-juicer/blob/main/README_ZH.md) 上的操作指引。

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking 先搜索，再提问

- [X] I have searched the Data-Juicer [issues](https://github.com/alibaba/data-juicer/issues) and found no similar questions. 我已经在 [issue列表](https://github.com/alibaba/data-juicer/issues) 中搜索但是没有发现类似的问题。

### Question

Thank you for sharing this great project. 
I am now attempting to train a Quality Classifier for other languages. 
Could you please tell me which base architecture (base model) you used for training the Quality Classifier (GPT3, and Chinese)?

**Comment by yxdyc** [comment]
Thanks for your interest! You can find the details on how to use our provided script to train your own classifier, as well as information about its underlying architecture (based on PySpark and LogisticRegression), in our [doc](https://github.com/modelscope/data-juicer/blob/da793458c70b4c034f0ba4bf03018b27febe12d1/tools/quality_classifier/README.md#train-your-own-quality-classifier).

**Comment by koanho** [comment]
Thank you for your kind reply :)
