### ISSUE TITLE
cache files in /tmp/hf_datasets-*

### ISSUE THREAD

**Issue by simplew2011** [modelscope/data-juicer#328]
### Before Asking 在提问之前

- [X] I have read the [README](https://github.com/alibaba/data-juicer/blob/main/README.md) carefully. 我已经仔细阅读了 [README](https://github.com/alibaba/data-juicer/blob/main/README_ZH.md) 上的操作指引。

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking 先搜索，再提问

- [X] I have searched the Data-Juicer [issues](https://github.com/alibaba/data-juicer/issues) and found no similar questions. 我已经在 [issue列表](https://github.com/alibaba/data-juicer/issues) 中搜索但是没有发现类似的问题。

### Question

- https://github.com/modelscope/data-juicer/blob/1c7bdc42d0673d96bc7a5c357902c14355f53766/data_juicer/core/data.py#L119
- in NestedDataset map and filter process
- In addition to the loading cache of huggingface datasets in `~/. cache/huggingface/datasets`
- during the processing, a large amount of cached data will also be generated in `/tmp/hf_datasets - *` directory, resulting in high disk usage

**Comment by simplew2011** [comment]
- 除了数据加载时会保存缓存文件在`~/. cache/huggingface/datasets`，之外
- `/tmp/hf_datasets -*`目录下也会生成较大的缓存文件夹，占用较大的磁盘

**Comment by HYLcool** [comment]
嗨 @simplew2011 

这个tmp目录与cache目录都是由huggingface datasets底层实现导致的，对于每个算子，datasets在处理过程当中会将处理中的一些临时结果存放与tmp目录中，在该算子处理结束后，再将整体的cache结果保存与cache目录下。而在整体的处理流程结束后，tmp目录中的结果会自动清除，而cache目录中结果则会保留（如果use_cache为true的话）
