### ISSUE TITLE
potential bug of checkpointing

### ISSUE THREAD

**Issue by drcege** [modelscope/data-juicer#337]
As the title suggests, the issue lies in the following code. 

https://github.com/modelscope/data-juicer/blob/c85e024c718b8e2dab967de478d15dc5db3dd907/data_juicer/utils/ckpt_utils.py#L86-L101

When the new `process_list` is shorter than `op_record`, Python does not raise an error for out-of-range indices but rather truncates to the maximum available length, thus `len(prefix_process) < len(self.op_record)`. Similarly, the `zip` function terminates at the shorter iterable's length. This results in the `check_ops_to_skip` function incorrectly assuming that the recorded operators match the prefix of the current operators list. 

 Is that the case? @HYLcool @yxdyc

**Comment by HYLcool** [comment]
Yes, that's a problem when meeting this situation. 👍🏻
