### ISSUE TITLE
How to download the YoukuMPLUG video dataset?

### ISSUE THREAD

**Issue by lucasjinreal** [modelscope/data-juicer#341]
the modelscope newestlib unable to download it any more.
Alos, is there a simple way to download the videos?

**Comment by yxdyc** [comment]
Thank you for reaching out. You can try `pip install modelscope[framework]` to install the necessary download-related [requirements](https://github.com/modelscope/modelscope/blob/master/requirements/framework.txt).

**Comment by lucasjinreal** [comment]
No, can u test with latest modelscope? it's some key error, nothing to do with the framework.....

**Comment by wangxingjun778** [comment]
Please refer to the discussion： https://modelscope.cn/datasets/modelscope/Youku-AliceMind/feedback/issueDetail/12827

**Comment by wangxingjun778** [comment]
Basically, due to the dependency `datasets` , it's not compatible with older version, the following method is recommended temporarily: pip install modelscope==1.7.1 ，and the issue will be fixed in the future version.

**Comment by lucasjinreal** [comment]
Any estimate time would align with latest modelscope? I am afraid make users using old modescope will break the latest repo which depends on latest modelscope, and, it's cubersome..

**Comment by wangxingjun778** [comment]
> Any estimate time would align with latest modelscope? I am afraid make users using old modescope will break the latest repo which depends on latest modelscope, and, it's cubersome..

 The version (1.16.1) of modelscope should be released within 2 weeks. )

**Comment by wangxingjun778** [comment]
Already merged. Try to install the latest version from source code:

https://github.com/modelscope/modelscope

pip3 install -e .
pip3 install -r requirements/datasets.txt

**Comment by wangxingjun778** [comment]
The latest installation and usage has been updated in the youku-mplug page, refer to:
https://modelscope.cn/datasets/modelscope/Youku-AliceMind
