### ISSUE TITLE
ram_plus_swin_large_14m.pth invalid

### ISSUE THREAD

**Issue by arturia-Xayah** [modelscope/data-juicer#350]
### Before Asking 在提问之前

- [X] I have read the [README](https://github.com/alibaba/data-juicer/blob/main/README.md) carefully. 我已经仔细阅读了 [README](https://github.com/alibaba/data-juicer/blob/main/README_ZH.md) 上的操作指引。

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking 先搜索，再提问

- [X] I have searched the Data-Juicer [issues](https://github.com/alibaba/data-juicer/issues) and found no similar questions. 我已经在 [issue列表](https://github.com/alibaba/data-juicer/issues) 中搜索但是没有发现类似的问题。

### Question

模型下载好了但没法加载

### Additional 额外信息

`2024-07-11 10:39:40.453 | INFO     | data_juicer:setup_mp:64 - Setting multiprocess start method to 'forkserver'.
2024-07-11 10:40:01 | WARNING  | data_juicer.config.config:422 - Cache management of datasets is disabled.
2024-07-11 10:40:01 | WARNING  | data_juicer.config.config:433 - Set temp directory to store temp files to [None].
2024-07-11 10:40:03 | INFO     | data_juicer.config.config:629 - Back up the input config file [/data/dj_sora_challenge/project_demo.yaml] into the work_dir [/data/dj_sora_challenge/output/processed_data]
2024-07-11 10:40:03 | INFO     | data_juicer.config.config:651 - Configuration table: 
╒════════════════════════════╤══════════════════════════════════════════════════════════════════════════════════╕
│ key                        │ values                                                                           │
╞════════════════════════════╪══════════════════════════════════════════════════════════════════════════════════╡
│ config                     │ [Path_fr(/data/dj_sora_challenge/project_demo.yaml)]                             │
├────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────┤
│ hpo_config                 │ None                                                                             │
├────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────┤
│ path_k_sigma_recipe        │ None                                                                             │
├────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────┤
│ path_model_feedback_recipe │ None                                                                             │
├────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────┤
│ model_infer_config         │ None                                                                             │
├────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────┤
│ model_train_config         │ None                                                                             │
├────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────┤
│ data_eval_config           │ None                                                                             │
├────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────┤
│ model_eval_config          │ None                                                                             │
├────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────┤
│ data_probe_algo            │ 'uniform'                                                                        │
├────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────┤
│ data_probe_ratio           │ 1.0                                                                              │
├────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────┤
│ project_name               │ 'ray-demo'                                                                       │
├────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────┤
│ executor_type              │ 'default'                                                                        │
├────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────┤
│ dataset_path               │ '/data/dj_sora_challenge/input/data.jsonl'                                       │
├────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────┤
│ export_path                │ '/data/dj_sora_challenge/output/processed_data/new.jsonl'                        │
├────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────┤
│ export_shard_size          │ 0                                                                                │
├────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────┤
│ export_in_parallel         │ False                                                                            │
├────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────┤
│ keep_stats_in_res_ds       │ False                                                                            │
├────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────┤
│ keep_hashes_in_res_ds      │ False                                                                            │
├────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────┤
│ np                         │ 12                                                                               │
├────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────┤
│ text_keys                  │ 'text'                                                                           │
├────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────┤
│ image_key                  │ 'images'                                                                         │
├────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────┤
│ image_special_token        │ '<__dj__image>'                                                                  │
├────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────┤
│ audio_key                  │ 'audios'                                                                         │
├────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────┤
│ audio_special_token        │ '<__dj__audio>'                                                                  │
├────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────┤
│ video_key                  │ 'videos'                                                                         │
├────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────┤
│ video_special_token        │ '<__dj__video>'                                                                  │
├────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────┤
│ eoc_special_token          │ '<|__dj__eoc|>'                                                                  │
├────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────┤
│ suffixes                   │ []                                                                               │
├────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────┤
│ use_cache                  │ False                                                                            │
├────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────┤
│ ds_cache_dir               │ '/root/.cache/huggingface/datasets'                                              │
├────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────┤
│ cache_compress             │ None                                                                             │
├────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────┤
│ use_checkpoint             │ True                                                                             │
├────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────┤
│ temp_dir                   │ None                                                                             │
├────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────┤
│ open_tracer                │ True                                                                             │
├────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────┤
│ op_list_to_trace           │ []                                                                               │
├────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────┤
│ trace_num                  │ 10                                                                               │
├────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────┤
│ op_fusion                  │ False                                                                            │
├────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────┤
│ process                    │ [{'video_duration_filter': {'accelerator': 'cpu',                                │
│                            │                             'any_or_all': 'any',                                 │
│                            │                             'audio_key': 'audios',                               │
│                            │                             'cpu_required': 1,                                   │
│                            │                             'image_key': 'images',                               │
│                            │                             'max_duration': 100,                                 │
│                            │                             'mem_required': 0,                                   │
│                            │                             'min_duration': 20,                                  │
│                            │                             'spec_numprocs': 0,                                  │
│                            │                             'text_key': 'text',                                  │
│                            │                             'use_actor': False,                                  │
│                            │                             'video_key': 'videos'}},                             │
│                            │  {'video_resolution_filter': {'accelerator': 'cpu',                              │
│                            │                               'any_or_all': 'any',                               │
│                            │                               'audio_key': 'audios',                             │
│                            │                               'cpu_required': 1,                                 │
│                            │                               'image_key': 'images',                             │
│                            │                               'max_height': 4096,                                │
│                            │                               'max_width': 4096,                                 │
│                            │                               'mem_required': 0,                                 │
│                            │                               'min_height': 200,                                 │
│                            │                               'min_width': 200,                                  │
│                            │                               'spec_numprocs': 0,                                │
│                            │                               'text_key': 'text',                                │
│                            │                               'use_actor': False,                                │
│                            │                               'video_key': 'videos'}},                           │
│                            │  {'video_remove_watermark_mapper': {'accelerator': 'cpu',                        │
│                            │                                     'audio_key': 'audios',                       │
│                            │                                     'batched_op': False,                         │
│                            │                                     'cpu_required': 1,                           │
│                            │                                     'detection_method': 'pixel_value',           │
│                            │                                     'frame_num': 10,                             │
│                            │                                     'image_key': 'images',                       │
│                            │                                     'mem_required': 0,                           │
│                            │                                     'min_frame_threshold': 7,                    │
│                            │                                     'roi_key': None,                             │
│                            │                                     'roi_strings': ['0,0,0.1,0.1'],              │
│                            │                                     'roi_type': 'ratio',                         │
│                            │                                     'spec_numprocs': 0,                          │
│                            │                                     'text_key': 'text',                          │
│                            │                                     'threshold': None,                           │
│                            │                                     'use_actor': False,                          │
│                            │                                     'video_key': 'videos'}},                     │
│                            │  {'video_split_by_duration_mapper': {'accelerator': 'cpu',                       │
│                            │                                      'audio_key': 'audios',                      │
│                            │                                      'batched_op': False,                        │
│                            │                                      'cpu_required': 1,                          │
│                            │                                      'image_key': 'images',                      │
│                            │                                      'keep_original_sample': True,               │
│                            │                                      'mem_required': 0,                          │
│                            │                                      'min_last_split_duration': 0.1,             │
│                            │                                      'spec_numprocs': 0,                         │
│                            │                                      'split_duration': 10,                       │
│                            │                                      'text_key': 'text',                         │
│                            │                                      'use_actor': False,                         │
│                            │                                      'video_key': 'videos'}},                    │
│                            │  {'video_tagging_from_frames_mapper': {'accelerator': 'cpu',                     │
│                            │                                        'audio_key': 'audios',                    │
│                            │                                        'batched_op': False,                      │
│                            │                                        'cpu_required': 1,                        │
│                            │                                        'frame_num': 3,                           │
│                            │                                        'frame_sampling_method': 'all_keyframes', │
│                            │                                        'image_key': 'images',                    │
│                            │                                        'mem_required': 0,                        │
│                            │                                        'spec_numprocs': 0,                       │
│                            │                                        'text_key': 'text',                       │
│                            │                                        'use_actor': False,                       │
│                            │                                        'video_key': 'videos'}}]                  │
├────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────┤
│ save_stats_in_one_file     │ False                                                                            │
├────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────┤
│ ray_address                │ 'auto'                                                                           │
├────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────┤
│ debug                      │ False                                                                            │
├────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────┤
│ work_dir                   │ '/data/dj_sora_challenge/output/processed_data'                                  │
├────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────┤
│ timestamp                  │ '20240711104000'                                                                 │
├────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────┤
│ dataset_dir                │ '/data/dj_sora_challenge/input'                                                  │
├────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────┤
│ add_suffix                 │ False                                                                            │
╘════════════════════════════╧══════════════════════════════════════════════════════════════════════════════════╛
2024-07-11 10:40:03 | INFO     | data_juicer.core.executor:54 - Setting up data formatter...
2024-07-11 10:40:03 | INFO     | data_juicer.core.executor:65 - Preparing checkpoint manager...
2024-07-11 10:40:03 | INFO     | data_juicer.core.executor:76 - Preparing exporter...
2024-07-11 10:40:03 | INFO     | data_juicer.core.executor:88 - Preparing tracer...
2024-07-11 10:40:03 | INFO     | data_juicer.core.executor:92 - Trace for all ops.
2024-07-11 10:40:03 | INFO     | data_juicer.core.executor:153 - Loading dataset from data formatter...
2024-07-11 10:40:04 | INFO     | data_juicer.format.formatter:185 - Unifying the input dataset formats...
2024-07-11 10:40:04 | INFO     | data_juicer.format.formatter:200 - There are 50000 sample(s) in the original dataset.

Filter (num_proc=12):   0%|          | 0/50000 [00:00<?, ? examples/s]
Filter (num_proc=12):   4%|4         | 2000/50000 [03:50<1:32:01,  8.69 examples/s]
Filter (num_proc=12):  38%|###8      | 19167/50000 [03:50<04:27, 115.21 examples/s]
Filter (num_proc=12): 100%|##########| 50000/50000 [03:54<00:00, 213.11 examples/s]
2024-07-11 10:44:01 | INFO     | data_juicer.format.formatter:214 - 50000 samples left after filtering empty text.
2024-07-11 10:44:01 | INFO     | data_juicer.format.formatter:237 - Converting relative paths in the dataset to their absolute version. (Based on the directory of input dataset file)

Map (num_proc=12):   0%|          | 0/50000 [00:00<?, ? examples/s]
Map (num_proc=12):   0%|          | 174/50000 [03:49<18:12:56,  1.32s/ examples]
Map (num_proc=12):   6%|6         | 3050/50000 [03:49<41:52, 18.69 examples/s]  
Map (num_proc=12):  21%|##        | 10337/50000 [03:49<07:55, 83.50 examples/s]
Map (num_proc=12):  35%|###5      | 17614/50000 [03:49<03:04, 175.76 examples/s]
Map (num_proc=12):  50%|#####     | 25112/50000 [03:49<01:19, 311.15 examples/s]
Map (num_proc=12):  66%|######5   | 32797/50000 [03:49<00:33, 508.45 examples/s]
Map (num_proc=12):  79%|#######9  | 39694/50000 [03:49<00:13, 759.47 examples/s]
Map (num_proc=12):  93%|#########2| 46391/50000 [03:49<00:03, 1102.18 examples/s]
Map (num_proc=12): 100%|##########| 50000/50000 [03:53<00:00, 214.28 examples/s] 
2024-07-11 10:47:58 | INFO     | data_juicer.format.mixture_formatter:137 - sampled 50000 from 50000
2024-07-11 10:47:58 | INFO     | data_juicer.format.mixture_formatter:143 - There are 50000 in final dataset
2024-07-11 10:47:58 | INFO     | data_juicer.core.executor:159 - Preparing process operators...
2024-07-11 10:47:59 | INFO     | data_juicer.utils.model_utils:509 - Loading recognizeAnything model...
2024-07-11 10:48:04 | INFO     | data_juicer.utils.model_utils:69 - Model [/root/.cache/data_juicer/models/ram_plus_swin_large_14m.pth] invalid, force to downloading...
2024-07-11 10:48:49 | ERROR    | __main__:19 - An error has been caught in function '<module>', process 'MainProcess' (3333217), thread 'MainThread' (140066013885568):
Traceback (most recent call last):

  File "/usr/local/lib/python3.10/dist-packages/data_juicer/utils/model_utils.py", line 511, in prepare_recognizeAnything_model
    model = ram_plus(pretrained=check_model(pretrained_model_name_or_path),
            │                   │           └ 'ram_plus_swin_large_14m.pth'
            │                   └ <function check_model at 0x7f62c9551c60>
            └ <function ram_plus at 0x7f6230f5f250>
  File "/usr/local/lib/python3.10/dist-packages/ram/models/ram_plus.py", line 403, in ram_plus
    model = RAM_plus(**kwargs)
            │          └ {'image_size': 384, 'vit': 'swin_l'}
            └ <class 'ram.models.ram_plus.RAM_plus'>
  File "/usr/local/lib/python3.10/dist-packages/ram/models/ram_plus.py", line 137, in __init__
    self.tokenizer = init_tokenizer(text_encoder_type)
    │                │              └ 'bert-base-uncased'
    │                └ <function init_tokenizer at 0x7f620e05e9e0>
    └ RAM_plus(
        (visual_encoder): SwinTransformer(
          (patch_embed): PatchEmbed(
            (proj): Conv2d(3, 192, kernel_size=(4, 4)...
  File "/usr/local/lib/python3.10/dist-packages/ram/models/utils.py", line 131, in init_tokenizer
    tokenizer = BertTokenizer.from_pretrained(text_encoder_type)
                │             │               └ 'bert-base-uncased'
                │             └ <classmethod(<function PreTrainedTokenizerBase.from_pretrained at 0x7f625b411d80>)>
                └ <class 'transformers.models.bert.tokenization_bert.BertTokenizer'>
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py", line 2013, in from_pretrained
    raise EnvironmentError(

OSError: Can't load tokenizer for 'bert-base-uncased'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'bert-base-uncased' is the correct path to a directory containing all relevant files for a BertTokenizer tokenizer.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

> File "/data/dj_sora_challenge/toolkit/data-juicer/tools/process_data.py", line 19, in <module>
    main()
    └ <function main at 0x7f6231380820>

  File "/data/dj_sora_challenge/toolkit/data-juicer/tools/process_data.py", line 15, in main
    executor.run()
    │        └ <function Executor.run at 0x7f6231380670>
    └ <data_juicer.core.executor.Executor object at 0x7f623141d2a0>

  File "/usr/local/lib/python3.10/dist-packages/data_juicer/core/executor.py", line 160, in run
    self.process_list, self.ops = load_ops(self.cfg.process,
    │    │             │    │     │        │    │   └ [{'video_duration_filter': {'min_duration': 20, 'max_duration': 100, 'any_or_all': 'any', 'text_key': 'text', 'image_key': 'i...
    │    │             │    │     │        │    └ Namespace(config=[Path_fr(/data/dj_sora_challenge/project_demo.yaml)], hpo_config=None, path_k_sigma_recipe=None, path_model_...
    │    │             │    │     │        └ <data_juicer.core.executor.Executor object at 0x7f623141d2a0>
    │    │             │    │     └ <function load_ops at 0x7f6242b4aa70>
    │    │             │    └ None
    │    │             └ <data_juicer.core.executor.Executor object at 0x7f623141d2a0>
    │    └ [{'video_duration_filter': {'min_duration': 20, 'max_duration': 100, 'any_or_all': 'any', 'text_key': 'text', 'image_key': 'i...
    └ <data_juicer.core.executor.Executor object at 0x7f623141d2a0>
  File "/usr/local/lib/python3.10/dist-packages/data_juicer/ops/load.py", line 28, in load_ops
    ops.append(OPERATORS.modules[op_name](**args))
    │   │      │         │       │          └ {'frame_sampling_method': 'all_keyframes', 'frame_num': 3, 'text_key': 'text', 'image_key': 'images', 'audio_key': 'audios', ...
    │   │      │         │       └ 'video_tagging_from_frames_mapper'
    │   │      │         └ <property object at 0x7f62c953b1f0>
    │   │      └ <data_juicer.utils.registry.Registry object at 0x7f62c6cd1120>
    │   └ <method 'append' of 'list' objects>
    └ [<data_juicer.ops.filter.video_duration_filter.VideoDurationFilter object at 0x7f623141fc70>, <data_juicer.ops.filter.video_r...
  File "/usr/local/lib/python3.10/dist-packages/data_juicer/ops/mapper/video_tagging_from_frames_mapper.py", line 62, in __init__
    self.model_key = prepare_model(
    │                └ <function prepare_model at 0x7f62c9552320>
    └ <data_juicer.ops.mapper.video_tagging_from_frames_mapper.VideoTaggingFromFramesMapper object at 0x7f6231046ec0>
  File "/usr/local/lib/python3.10/dist-packages/data_juicer/utils/model_utils.py", line 545, in prepare_model
    model_objects = model_key()
                    └ functools.partial(<function prepare_recognizeAnything_model at 0x7f62c9552290>, pretrained_model_name_or_path='ram_plus_swin_...
  File "/usr/local/lib/python3.10/dist-packages/data_juicer/utils/model_utils.py", line 515, in prepare_recognizeAnything_model
    model = ram_plus(pretrained=check_model(pretrained_model_name_or_path,
            │                   │           └ 'ram_plus_swin_large_14m.pth'
            │                   └ <function check_model at 0x7f62c9551c60>
            └ <function ram_plus at 0x7f6230f5f250>
  File "/usr/local/lib/python3.10/dist-packages/ram/models/ram_plus.py", line 403, in ram_plus
    model = RAM_plus(**kwargs)
            │          └ {'image_size': 384, 'vit': 'swin_l'}
            └ <class 'ram.models.ram_plus.RAM_plus'>
  File "/usr/local/lib/python3.10/dist-packages/ram/models/ram_plus.py", line 137, in __init__
    self.tokenizer = init_tokenizer(text_encoder_type)
    │                │              └ 'bert-base-uncased'
    │                └ <function init_tokenizer at 0x7f620e05e9e0>
    └ RAM_plus(
        (visual_encoder): SwinTransformer(
          (patch_embed): PatchEmbed(
            (proj): Conv2d(3, 192, kernel_size=(4, 4)...
  File "/usr/local/lib/python3.10/dist-packages/ram/models/utils.py", line 131, in init_tokenizer
    tokenizer = BertTokenizer.from_pretrained(text_encoder_type)
                │             │               └ 'bert-base-uncased'
                │             └ <classmethod(<function PreTrainedTokenizerBase.from_pretrained at 0x7f625b411d80>)>
                └ <class 'transformers.models.bert.tokenization_bert.BertTokenizer'>
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py", line 2013, in from_pretrained
    raise EnvironmentError(

OSError: Can't load tokenizer for 'bert-base-uncased'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'bert-base-uncased' is the correct path to a directory containing all relevant files for a BertTokenizer tokenizer.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/data_juicer/utils/model_utils.py", line 511, in prepare_recognizeAnything_model
    model = ram_plus(pretrained=check_model(pretrained_model_name_or_path),
  File "/usr/local/lib/python3.10/dist-packages/ram/models/ram_plus.py", line 403, in ram_plus
    model = RAM_plus(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ram/models/ram_plus.py", line 137, in __init__
    self.tokenizer = init_tokenizer(text_encoder_type)
  File "/usr/local/lib/python3.10/dist-packages/ram/models/utils.py", line 131, in init_tokenizer
    tokenizer = BertTokenizer.from_pretrained(text_encoder_type)
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py", line 2013, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for 'bert-base-uncased'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'bert-base-uncased' is the correct path to a directory containing all relevant files for a BertTokenizer tokenizer.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/dj_sora_challenge/toolkit/data-juicer/tools/process_data.py", line 19, in <module>
    main()
  File "/usr/local/lib/python3.10/dist-packages/loguru/_logger.py", line 1277, in catch_wrapper
    return function(*args, **kwargs)
  File "/data/dj_sora_challenge/toolkit/data-juicer/tools/process_data.py", line 15, in main
    executor.run()
  File "/usr/local/lib/python3.10/dist-packages/data_juicer/core/executor.py", line 160, in run
    self.process_list, self.ops = load_ops(self.cfg.process,
  File "/usr/local/lib/python3.10/dist-packages/data_juicer/ops/load.py", line 28, in load_ops
    ops.append(OPERATORS.modules[op_name](**args))
  File "/usr/local/lib/python3.10/dist-packages/data_juicer/ops/mapper/video_tagging_from_frames_mapper.py", line 62, in __init__
    self.model_key = prepare_model(
  File "/usr/local/lib/python3.10/dist-packages/data_juicer/utils/model_utils.py", line 545, in prepare_model
    model_objects = model_key()
  File "/usr/local/lib/python3.10/dist-packages/data_juicer/utils/model_utils.py", line 515, in prepare_recognizeAnything_model
    model = ram_plus(pretrained=check_model(pretrained_model_name_or_path,
  File "/usr/local/lib/python3.10/dist-packages/ram/models/ram_plus.py", line 403, in ram_plus
    model = RAM_plus(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ram/models/ram_plus.py", line 137, in __init__
    self.tokenizer = init_tokenizer(text_encoder_type)
  File "/usr/local/lib/python3.10/dist-packages/ram/models/utils.py", line 131, in init_tokenizer
    tokenizer = BertTokenizer.from_pretrained(text_encoder_type)
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py", line 2013, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for 'bert-base-uncased'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'bert-base-uncased' is the correct path to a directory containing all relevant files for a BertTokenizer tokenizer.
`

**Comment by drcege** [comment]
这是 `ram_plus` 内部机制问题，代码 `tokenizer = BertTokenizer.from_pretrained(text_encoder_type)` 需要从 HuggingFace 下载 `bert-base-uncased` tokenizer。

请在可访问的网络下运行，或者在以下代码中通过 text_encoder_type 参数传入本地路径：
https://github.com/modelscope/data-juicer/blob/619da1aef2763298960e005e901c2eabebb3b915/data_juicer/utils/model_utils.py#L511-L513

**Comment by arturia-Xayah** [comment]
夏眠中...
