### ISSUE TITLE
video_ocr_area_ratio_filter may cause cuda out of memory

### ISSUE THREAD

**Issue by ycwfs** [modelscope/data-juicer#353]
### Before Asking 在提问之前

- [X] I have read the [README](https://github.com/alibaba/data-juicer/blob/main/README.md) carefully. 我已经仔细阅读了 [README](https://github.com/alibaba/data-juicer/blob/main/README_ZH.md) 上的操作指引。

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking 先搜索，再提问

- [X] I have searched the Data-Juicer [issues](https://github.com/alibaba/data-juicer/issues) and found no similar questions. 我已经在 [issue列表](https://github.com/alibaba/data-juicer/issues) 中搜索但是没有发现类似的问题。

### Question

我在使用video_ocr_area_ratio_filter这个算子时遇到的，由于我的np设置为40，而这个算子的easyocr模型使用了gpu加速，但没有像其它huggingface等模型一样加载，也就没有参与calculate_np计算来调整np，且一个模型大概占2G多显存，导致此问题。
我看了下代码，因为easyocr的reader在初始化时就要指定device，不改动prepare，get_model就不太好修改。

**Comment by drcege** [comment]
请测试 #354 是否能解决？

**Comment by ycwfs** [comment]
> 请测试 #354 是否能解决？

略有修改#357 ，测试能行
