### ISSUE TITLE
[Bug]: RuntimeError: SimpleQueue objects should only be shared between processes through inheritance

### ISSUE THREAD

**Issue by MingdongHe** [modelscope/data-juicer#356]
### Before Reporting 报告之前

- [X] I have pulled the latest code of main branch to run again and the bug still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

- [X] I have read the [README](https://github.com/alibaba/data-juicer/blob/main/README.md) carefully and no error occurred during the installation process. (Otherwise, we recommend that you can ask a question using the Question template) 我已经仔细阅读了 [README](https://github.com/alibaba/data-juicer/blob/main/README_ZH.md) 上的操作指引，并且在安装过程中没有错误发生。（否则，我们建议您使用Question模板向我们进行提问）

### Search before reporting 先搜索，再报告

- [X] I have searched the Data-Juicer [issues](https://github.com/alibaba/data-juicer/issues) and found no similar bugs. 我已经在 [issue列表](https://github.com/alibaba/data-juicer/issues) 中搜索但是没有发现类似的bug报告。

### OS 系统

ubuntu

### Installation Method 安装方式

git pull origin main || true pip install '.[all]'

### Python Version Python版本

3.10

### Describe the bug 描述这个bug

![image](https://github.com/user-attachments/assets/f6f8020c-6b9a-4101-944c-46c305308bb9)

### To Reproduce 如何复现

python tools/process_data.py --config configs/demo/process.yaml
运行这个命令报错

**Comment by drcege** [comment]
麻烦补充下当前 data_juicer 的 commit id 和 pip list 的结果；初步建议排查 datasets, multiprocess, dill 的版本是否满足要求。

**Comment by MingdongHe** [comment]
commit c85e024c718b8e2dab967de478d15dc5db3dd907
Package                       Version
----------------------------- ------------------
absl-py                       2.1.0
accelerate                    0.31.0
addict                        2.4.0
aiohttp                       3.9.5
aiosignal                     1.3.1
alabaster                     0.7.16
altair                        5.3.0
annotated-types               0.7.0
antlr4-python3-runtime        4.9.3
anyio                         4.4.0
archspec                      0.2.3
astor                         0.8.1
asttokens                     2.2.1
async-timeout                 4.0.3
attrs                         23.2.0
audioread                     3.0.1
av                            12.2.0
Babel                         2.15.0
backcall                      0.2.0
bce-python-sdk                0.9.14
beautifulsoup4                4.12.3
black                         24.4.2
blinker                       1.8.2
blis                          0.7.11
boltons                       23.0.0
boto3                         1.34.140
botocore                      1.34.140
Bottleneck                    1.3.7
Brotli                        1.0.9
cachetools                    5.3.3
catalogue                     2.0.10
certifi                       2024.6.2
cffi                          1.16.0
cfgv                          3.4.0
chardet                       4.0.0
charset-normalizer            3.3.2
click                         8.1.7
cloudpickle                   3.0.0
colorama                      0.4.6
comm                          0.1.4
commonmark                    0.9.1
conda                         24.5.0
conda-libmamba-solver         24.1.0
conda-package-handling        2.3.0
conda_package_streaming       0.10.0
confection                    0.1.5
contourpy                     1.2.1
cryptography                  42.0.8
cycler                        0.12.1
cymem                         2.0.8
Cython                        3.0.10
datasets                      2.18.0
debugpy                       1.6.7.post1
decorator                     5.1.1
decord                        0.6.0
deepspeed                     0.14.4
diffusers                     0.27.0
dill                          0.3.4
distlib                       0.3.8
distro                        1.9.0
dlib                          19.24.4
docstring_parser              0.16
docutils                      0.20.1
easydict                      1.13
easyocr                       1.7.1
einops                        0.8.0
emoji                         2.2.0
exceptiongroup                1.2.1
executing                     1.2.0
facexlib                      0.3.0
fairscale                     0.4.13
fasttext-wheel                0.9.2
ffmpeg-python                 0.2.0
filelock                      3.13.1
filterpy                      1.4.5
fire                          0.6.0
Flask                         3.0.3
flask-babel                   4.0.0
flatbuffers                   23.5.26
fonttools                     4.53.0
frozendict                    2.4.2
frozenlist                    1.4.0
fsspec                        2023.5.0
ftfy                          6.2.0
func_timeout                  4.3.5
future                        1.0.0
fvcore                        0.1.5.post20221221
gdown                         5.2.0
gitdb                         4.0.11
GitPython                     3.1.43
gmpy2                         2.1.2
grpcio                        1.64.1
h11                           0.14.0
hjson                         3.1.0
httpcore                      1.0.5
httpx                         0.27.0
huggingface-hub               0.23.4
humanfriendly                 10.0
hydra-core                    1.3.2
icecream                      2.1.3
identify                      2.5.36
idna                          3.7
imagededup                    0.3.2
imageio                       2.34.2
imageio-ffmpeg                0.5.1
imagesize                     1.4.1
imgaug                        0.4.0
importlib_metadata            8.0.0
importlib_resources           6.4.0
iopath                        0.1.9
ipykernel                     6.25.1
ipython                       8.14.0
itsdangerous                  2.2.0
jedi                          0.19.0
jieba                         0.42.1
Jinja2                        3.1.4
jmespath                      1.0.1
joblib                        1.4.2
jsonargparse                  4.31.0
jsonlines                     4.0.0
jsonpatch                     1.33
jsonpointer                   2.1
jsonschema                    4.22.0
jsonschema-specifications     2023.12.1
jupyter_client                8.3.0
jupyter_core                  5.3.1
kenlm                         0.2.0
kiwisolver                    1.4.5
langcodes                     3.4.0
language_data                 1.2.0
lap                           0.4.0
lazy_loader                   0.4
libmambapy                    1.5.8
librosa                       0.10.2.post1
llvmlite                      0.43.0
lmdb                          1.5.1
loguru                        0.7.2
lvis                          0.5.3
lxml                          5.2.2
lz4                           4.3.3
marisa-trie                   1.2.0
Markdown                      3.6
markdown-it-py                3.0.0
MarkupSafe                    2.1.5
matplotlib                    3.9.0
matplotlib-inline             0.1.6
mdurl                         0.1.2
menuinst                      2.1.1
mkl-fft                       1.3.8
mkl-random                    1.2.4
mkl-service                   2.4.0
motmetrics                    1.4.0
mpmath                        1.3.0
msgpack                       1.0.8
multidict                     6.0.4
multiprocess                  0.70.12
murmurhash                    1.0.10
mypy-extensions               1.0.0
nest-asyncio                  1.5.7
networkx                      3.3
ninja                         1.11.1.1
nlpaug                        1.1.11
nlpcda                        2.5.8
nltk                          3.8.1
nodeenv                       1.9.1
numba                         0.60.0
numexpr                       2.8.7
numpy                         1.23.5
nvidia-cublas-cu11            11.10.3.66
nvidia-cublas-cu12            12.1.3.1
nvidia-cuda-cupti-cu12        12.1.105
nvidia-cuda-nvrtc-cu11        11.7.99
nvidia-cuda-nvrtc-cu12        12.1.105
nvidia-cuda-runtime-cu11      11.7.99
nvidia-cuda-runtime-cu12      12.1.105
nvidia-cudnn-cu11             8.5.0.96
nvidia-cudnn-cu12             8.9.2.26
nvidia-cufft-cu12             11.0.2.54
nvidia-curand-cu12            10.3.2.106
nvidia-cusolver-cu12          11.4.5.107
nvidia-cusparse-cu12          12.1.0.106
nvidia-ml-py                  12.555.43
nvidia-nccl-cu12              2.20.5
nvidia-nvjitlink-cu12         12.5.40
nvidia-nvtx-cu12              12.1.105
omegaconf                     2.3.0
openai-clip                   1.0.1
OpenCC                        1.1.6
opencv-python                 4.5.5.64
opencv-python-headless        4.10.0.84
opt-einsum                    3.3.0
packaging                     24.1
pandas                        2.0.3
parso                         0.8.3
pathlib_abc                   0.1.1
pathspec                      0.12.1
pathy                         0.11.0
pdfminer.six                  20231228
pdfplumber                    0.11.1
pexpect                       4.4.0
pickleshare                   0.7.5
pillow                        10.3.0
pip                           24.0
platformdirs                  3.10.0
plotly                        5.22.0
pluggy                        1.0.0
pooch                         1.8.2
portalocker                   2.10.0
pre-commit                    3.7.1
preshed                       3.0.9
prompt-toolkit                3.0.39
protobuf                      4.25.3
psutil                        6.0.0
ptyprocess                    0.7.0
pure-eval                     0.2.2
py-cpuinfo                    9.0.0
py-data-juicer                0.2.0
py4j                          0.10.9.7
pyarrow                       12.0.0
pyarrow-hotfix                0.6
pybind11                      2.13.1
pyclipper                     1.3.0.post5
pycocotools                   2.0.8
pycosat                       0.6.6
pycparser                     2.21
pycryptodome                  3.20.0
pydantic                      1.10.17
pydantic_core                 2.18.4
pydeck                        0.9.1
Pygments                      2.16.1
pyiqa                         0.1.11
pyparsing                     3.1.2
pypdfium2                     4.30.0
PySocks                       1.7.1
pyspark                       3.5.1
python-bidi                   0.4.2
python-dateutil               2.8.2
python-docx                   1.1.2
pytz                          2024.1
PyWavelets                    1.6.0
PyYAML                        6.0.1
pyzmq                         25.1.1
rarfile                       4.2
ray                           2.10.0
recommonmark                  0.7.1
redis                         5.0.7
referencing                   0.35.1
regex                         2023.10.3
requests                      2.32.3
rich                          13.7.1
rpds-py                       0.18.1
ruamel.yaml                   0.17.21
ruamel.yaml.clib              0.2.6
s3transfer                    0.10.2
safetensors                   0.4.2
scenedetect                   0.6.4
scikit-image                  0.24.0
scikit-learn                  1.5.0
scipy                         1.13.1
seaborn                       0.13.2
selectolax                    0.3.21
sentencepiece                 0.2.0
setuptools                    70.3.0
shapely                       2.0.4
simhash-pybind                0.0.3
simple-aesthetics-predictor   0.1.2
six                           1.16.0
sklearn                       0.0
smart-open                    6.4.0
smmap                         5.0.1
sniffio                       1.3.1
snowballstemmer               2.2.0
soundfile                     0.12.1
soupsieve                     2.5
soxr                          0.3.7
spacy                         3.5.0
spacy-legacy                  3.0.12
spacy-loggers                 1.0.5
spacy-pkuseg                  0.0.32
Sphinx                        7.3.7
sphinx-autobuild              2024.4.16
sphinx-rtd-theme              2.0.0
sphinxcontrib-applehelp       1.0.8
sphinxcontrib-devhelp         1.0.6
sphinxcontrib-htmlhelp        2.0.5
sphinxcontrib-jquery          4.1
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.7
sphinxcontrib-serializinghtml 1.1.10
srsly                         2.4.8
stack-data                    0.6.2
starlette                     0.37.2
streamlit                     1.36.0
sympy                         1.12
tabulate                      0.9.0
tenacity                      8.4.2
tensorboard                   2.17.0
tensorboard-data-server       0.7.2
termcolor                     2.4.0
terminaltables                3.1.10
thinc                         8.1.12
threadpoolctl                 3.5.0
tifffile                      2024.6.18
tiktoken                      0.7.0
timm                          1.0.7
tokenizers                    0.15.2
toml                          0.10.2
tomli                         2.0.1
toolz                         0.12.1
torch                         2.3.0
torchaudio                    0.13.1
torchvision                   0.18.0
tornado                       6.3.3
tqdm                          4.66.4
traitlets                     5.9.0
transformers                  4.37.2
transformers-stream-generator 0.0.5
triton                        2.3.0
truststore                    0.8.0
typeguard                     4.3.0
typer                         0.7.0
typeshed_client               2.5.1
typing_extensions             4.12.2
tzdata                        2024.1
urllib3                       2.2.2
uvicorn                       0.30.1
virtualenv                    20.26.3
visualdl                      2.5.3
wasabi                        1.1.3
watchdog                      4.0.1
watchfiles                    0.22.0
wcwidth                       0.2.13
websockets                    12.0
Werkzeug                      3.0.3
wget                          3.2
wheel                         0.43.0
xformers                      0.0.26.post1
xmltodict                     0.13.0
xxhash                        2.0.2
yacs                          0.1.8
yapf                          0.40.2
yarl                          1.9.3
zipp                          3.19.2
zstandard                     0.22.0

**Comment by drcege** [comment]
提供的 pip 列表与截图中的环境不匹配，是否调用了错误的 pip 路径？

经核实，dill 实际版本为 0.3.8；请安装 dill==0.3.4 可解决。

**Comment by MingdongHe** [comment]
确实显示的dill==0.3.4,运行会出错，然后我pip install dill==0.3.4他会提示已经满足要求，之后我卸载然后重新安装dill==0.3.4,问题解决了，谢谢
