### ISSUE TITLE
请问如何在自己的文档数据上通过GPT-4o/Claude3.5-Sonnet预标注，清洗，最后制作成一个VQA的数据集？

### ISSUE THREAD

**Issue by moyans** [modelscope/data-juicer#360]
### Before Asking 在提问之前

- [X] I have read the [README](https://github.com/alibaba/data-juicer/blob/main/README.md) carefully. 我已经仔细阅读了 [README](https://github.com/alibaba/data-juicer/blob/main/README_ZH.md) 上的操作指引。

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking 先搜索，再提问

- [X] I have searched the Data-Juicer [issues](https://github.com/alibaba/data-juicer/issues) and found no similar questions. 我已经在 [issue列表](https://github.com/alibaba/data-juicer/issues) 中搜索但是没有发现类似的问题。

### Question

我希望在自己的文档数据上通过GPT-4o/Claude3.5-Sonnet....预标注，清洗，最后制作成一个VQA的数据集？很抱歉未能通过教程找到答案，希望有懂的老师帮忙指引，解惑。

**Comment by drcege** [comment]
目前提供了 `image_captioning_from_gpt4v_mapper.py` 调用 `gpt-4-vision-preview` 接口对图像进行描述。GPT-4o 接口可能有变化，需要相应调整

**Comment by moyans** [comment]
感谢
