### ISSUE TITLE
[Bug]: librosa not work with np>1

### ISSUE THREAD

**Issue by drcege** [modelscope/data-juicer#372]
The involved OPs, such as `audio_duration_filter` and `audio_nmf_snr_filter`, encounter errors when `np > 1`. Initial diagnosis points to an issue with librosa.

![image](https://github.com/user-attachments/assets/4f5263a3-275f-4f79-abad-81f85e100f2e)

![image](https://github.com/user-attachments/assets/4386e265-08ee-4007-b0b5-f36cbefd7e5a)

**Comment by HYLcool** [comment]
It's solved by installing `samplerate` and `resampy` before data processing, which will be loaded lazily in `librosa` and might cause multiprocessing problems.

These two dependencies have been added to the requirement files now.
