### ISSUE TITLE
[Bug]: 使用图片相关算子在显存充足的情况下 报OOM 

### ISSUE THREAD

**Issue by tian969** [modelscope/data-juicer#378]
### Before Reporting 报告之前

- [X] I have pulled the latest code of main branch to run again and the bug still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

- [X] I have read the [README](https://github.com/alibaba/data-juicer/blob/main/README.md) carefully and no error occurred during the installation process. (Otherwise, we recommend that you can ask a question using the Question template) 我已经仔细阅读了 [README](https://github.com/alibaba/data-juicer/blob/main/README_ZH.md) 上的操作指引，并且在安装过程中没有错误发生。（否则，我们建议您使用Question模板向我们进行提问）

### Search before reporting 先搜索，再报告

- [X] I have searched the Data-Juicer [issues](https://github.com/alibaba/data-juicer/issues) and found no similar bugs. 我已经在 [issue列表](https://github.com/alibaba/data-juicer/issues) 中搜索但是没有发现类似的bug报告。

### OS 系统

Ubuntu 

### Installation Method 安装方式

pip

### Data-Juicer Version Data-Juicer版本

v0.2.0

### Python Version Python版本

3.10

### Describe the bug 描述这个bug

我在使用image_text_similarity_filter 和 image_text_match_filter这两个算子时, 加载模型后运算时会报OOM, 并且对应的本应该计算得到的dj_stats为空. 但是nvidia-smi显存占用看起来没有满.
![image](https://github.com/user-attachments/assets/e49a8d28-edec-47b3-ac02-e7ea2f6cfe83)
报错信息如下:
![image](https://github.com/user-attachments/assets/0dc61cda-408c-4a69-b639-6c581a3b1e4a)
处理过程中的显存占用图:
![Snipaste_2024-08-02_10-19-14](https://github.com/user-attachments/assets/295fa922-8a13-44c4-9920-ddaf82436e68)

### To Reproduce 如何复现

配置信息如下所示:
![image](https://github.com/user-attachments/assets/470a76dd-ffd4-419a-86a1-6a875dc8f7d8)
只使用了这两个算子, np数开的8, 在A800下运行. 这两个算子使用的都是hugging face上的模型, 无论从缓存加载, 还是我本地指定模型路径, 都会出现相同的问题.
代码改动:
我只在加载模型时加入了一句print("1111") 和 固定从绝对路径加载(没改之前就有这个问题). 

### Configs 配置信息

![image](https://github.com/user-attachments/assets/12f42c68-fb4e-4570-985e-112551653cb2)

### Logs 报错日志

[export_stage1_dj_format_refined.jsonl_time_20240802101038.txt](https://github.com/user-attachments/files/16464530/export_stage1_dj_format_refined.jsonl_time_20240802101038.txt)

**Comment by tian969** [comment]
我使用transformer给出的示例, 加载并使用这两个模型, 看起来都是正常的. 我也使用了alphanumeric_filter.py 这个算子需要的模型, 能正常加载并使用得到dj_stats信息

**Comment by tian969** [comment]
我重新跑了一遍, 这次没有处理
![image](https://github.com/user-attachments/assets/c76e83ce-e4c1-4c11-adf6-dc6429bbc694)

**Comment by HYLcool** [comment]
嗨你好，感谢你使用DJ以及参与BetterSynth比赛！

OOM的问题我们暂时没能复现，如果你那边后续还是会遇到这个问题的话可以给我们提供更详细的一些信息~

至于stats计算为空的问题，主要为DJ目前的一个尚未解决的bug导致的，即config文件中image_special_token在cuda模式下无效的bug，这个问题我们正在想办法解决。目前有两个方法可以暂时绕过这个问题：
1. 直接基于比赛套件中下载的数据文件`mgm_pretrain_stage_1.jsonl`进行处理，我注意到你输入的数据集中image_special_token为“<image>"，而套件中下赛的数据文件已经全部替换为DJ默认的"<__dj__image>"，可以不用设置image_special_token参数
2. 在data-juicer代码中，将`data_juicer/utils/mm_utils.py`文件里SpecialTokens类中的image直接改为'<image>'，这样可以绕开image_special_token参数不生效的问题

你可以先尝试一下，如还有后续问题可随时沟通~

**Comment by tian969** [comment]
OK 按您说的方法解决了 再次启动的时候没有报OOM的问题 感谢~
