### ISSUE TITLE
[Bug]: 运行sandbox的时候显示ModuleNotFoundError: No module named 'tools.mm_eval'

### ISSUE THREAD

**Issue by Snow0111** [modelscope/data-juicer#379]
### Before Reporting 报告之前

- [X] I have pulled the latest code of main branch to run again and the bug still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

- [X] I have read the [README](https://github.com/alibaba/data-juicer/blob/main/README.md) carefully and no error occurred during the installation process. (Otherwise, we recommend that you can ask a question using the Question template) 我已经仔细阅读了 [README](https://github.com/alibaba/data-juicer/blob/main/README_ZH.md) 上的操作指引，并且在安装过程中没有错误发生。（否则，我们建议您使用Question模板向我们进行提问）

### Search before reporting 先搜索，再报告

- [X] I have searched the Data-Juicer [issues](https://github.com/alibaba/data-juicer/issues) and found no similar bugs. 我已经在 [issue列表](https://github.com/alibaba/data-juicer/issues) 中搜索但是没有发现类似的bug报告。

### OS 系统

Ubuntu

### Installation Method 安装方式

源码编译

### Python Version Python版本

3.8

### Describe the bug 描述这个bug

按照readme上面，拉下来源码，进入目录cd <path_to_data_juicer>
pip install -v -e .  # 安装最小依赖，支持基础功能
pip install -v -e .[tools] # 安装部分工具库的依赖
pip install -v -e .[sandbox] 并且安装依赖，
运行python3 tools/sandbox_starter.py --config configs/demo/sandbox/sandbox.yaml命令时候，报错
"xx/data-juicer/data_juicer/core/sandbox/evaluators.py", line 10, in <module>
    from tools.mm_eval.inception_metrics.calc_metrics_for_videos import \
ModuleNotFoundError: No module named 'tools.mm_eval'

### To Reproduce 如何复现

没有改任何代码
运行python3 tools/sandbox_starter.py --config configs/demo/sandbox/sandbox.yaml命令时候，报错
"xx/data-juicer/data_juicer/core/sandbox/evaluators.py", line 10, in <module>
    from tools.mm_eval.inception_metrics.calc_metrics_for_videos import \
ModuleNotFoundError: No module named 'tools.mm_eval'

### Screenshots 截图

![image](https://github.com/user-attachments/assets/05282551-d170-4ec7-a7cd-286e9637a4b1)

**Comment by BeachWang** [comment]
你好，

**Comment by Snow0111** [comment]
wandb: Network error (ConnectTimeout), entering retry loop.您好这个问题怎么解决呢

**Comment by drcege** [comment]
请检查 wandb 配置是否有误，或者到 wandb server 的网络连接是否被屏蔽
