### ISSUE TITLE
Confused with the meaning of 'preprocess' time-consuming in the `reproduced_redpajama /README.md`

### ISSUE THREAD

**Issue by flyflypeng** [modelscope/data-juicer#383]
I am confused with the `preprocess` and `read+unify` stage meaning in  `configs/reproduced_redpajama/README.md`, could you explain in more detail about the meaning of these two stages?

![image](https://github.com/user-attachments/assets/70d8c994-b664-42da-aa13-1d6401d67a7b)

**Comment by HYLcool** [comment]
Hi, thanks for your interest in Data-Juicer!

Here we compare the end-to-end time, so in addition to data cleaning and processing, there are some "preprocess" done before, such as format conversion mentioned before this table in the same markdown file. The arXiv data are downloaded as raw LaTeX sources, so we need to convert them to a JSONL file for later processing.
<img width="1110" alt="image" src="https://github.com/user-attachments/assets/2bf4fbc3-e682-431a-b9f7-d59ebd5d4e6f">

As for the "read+unify" stage, it's the necessary stage in Data-Juicer when loading a JSONL dataset from the previous "preprocess" stage. Data-Juicer would load this file, check the correctness of the dataset structure, unify the meta fields, and so on. For more details about this stage, please refer to the `unify_format` function in [formatter code](https://github.com/modelscope/data-juicer/blob/986b43d446e2894ce730f1cb9cc6778ea2da5b29/data_juicer/format/formatter.py#L147).

**Comment by flyflypeng** [comment]
Thanks a lot! Maybe `preprocess` and `read+unify` can be summarized as `Formatter` type operator  😄
