### ISSUE TITLE
什么鬼呀，不管是你们huggingface空间还是自己起个服务都运行不起来，demo也运行不起来

### ISSUE THREAD

**Issue by coder4nlp** [modelscope/data-juicer#404]
AxiosError: Request failed with status code 403

**Comment by zhijianma** [comment]
- huggingface 的spaces 使用的共享免费资源，超过一定时间后服务的容器被回收了，目前已重新上线。
- 本地起的哪个服务遇到了问题导致无法运行？

**Comment by yxdyc** [comment]
Issue fixed. It can be reopened if the problem reoccur or further clarification is needed.
