### ISSUE TITLE
analyzer or analyzer?

### ISSUE THREAD

**Issue by lilqz66** [modelscope/data-juicer#409]
### Before Asking 在提问之前

- [X] I have read the [README](https://github.com/alibaba/data-juicer/blob/main/README.md) carefully. 我已经仔细阅读了 [README](https://github.com/alibaba/data-juicer/blob/main/README_ZH.md) 上的操作指引。

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking 先搜索，再提问

- [X] I have searched the Data-Juicer [issues](https://github.com/alibaba/data-juicer/issues) and found no similar questions. 我已经在 [issue列表](https://github.com/alibaba/data-juicer/issues) 中搜索但是没有发现类似的问题。

### Question

![yaml](https://github.com/user-attachments/assets/c7f6ed9f-e2a4-4797-8ca6-192891442a3f)

![doc](https://github.com/user-attachments/assets/f96619fd-0174-4acf-899b-932ad4327fb3)

文档里为analyzer.yaml，文件里为analyser.yaml

**Comment by garyzhang99** [comment]
Thank you for your feedback. To maintain consistency, we use "analyzer" instead of "analyser" throughout the documentation and files. The name of the yaml file is fixed in https://github.com/modelscope/data-juicer/pull/410
