### ISSUE TITLE
[Feat] Support `PythonCodesOperator` and `BashCodesOperator` that wraps an existing python file, or some code snippets to be executed, such as the existing DJ tools.

### ISSUE THREAD

**Issue by yxdyc** [modelscope/data-juicer#412]
### Search before continuing 先搜索，再继续

- [X] I have searched the Data-Juicer issues and found no similar feature requests. 我已经搜索了 Data-Juicer 的 issue 列表但是没有发现类似的功能需求。

### Description 描述

Often, users require the integration of specific Data-Juicer tools, custom functionalities encapsulated within some `helper_func.py`, or some short Python scripts, such as a few lambda functions. These may not warrant the creation of a dedicated Operator due to the additional overhead involved, including subclassing, documentation, and unit testing.

To enhance flexibility and cater to diverse user needs, introducing some OPs that seamlessly incorporates existing Python files or executes code snippets would be beneficial. This approach enables users to enrich their data recipe configurations with a wider array of tools and custom code, which can be managed through a streamlined `PythonCodesOperator` and `BashCodesOperator` mechanism.

### Are you willing to submit a PR for this feature? 您是否乐意为此功能提交一个 PR？

- [X] Yes I'd like to help by submitting a PR! 是的！我愿意提供帮助并提交一个PR！

**Comment by yxdyc** [comment]
WIP: add basic abstraction and implementation for `ScriptOP` and some leaf classes such as `PythonCodesOperator` and `BashCodesOperator`, @drcege @BeachWang

**Comment by HYLcool** [comment]
This feature request has been implemented in #492 and #493 by @drcege and @BeachWang .
