### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by abchbx** [modelscope/data-juicer#420]
### Before Asking 在提问之前

- [X] I have read the [README](https://github.com/alibaba/data-juicer/blob/main/README.md) carefully. 我已经仔细阅读了 [README](https://github.com/alibaba/data-juicer/blob/main/README_ZH.md) 上的操作指引。

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking 先搜索，再提问

- [X] I have searched the Data-Juicer [issues](https://github.com/alibaba/data-juicer/issues) and found no similar questions. 我已经在 [issue列表](https://github.com/alibaba/data-juicer/issues) 中搜索但是没有发现类似的问题。

### Question

<img width="361" alt="111111" src="https://github.com/user-attachments/assets/e1a708b8-4aa9-475f-ab60-be81c7636946">

我在执行python tools/analyze_data.py --config xxx.yaml 分析 数据的时候显示报了这个错误，因为我原来操作过一遍，没用任何问题，今天使用报这个错误，是什么原因？请各位大佬指点一二

**Comment by drcege** [comment]
@abchbx 问题已经修复，请尝试最新代码
