### ISSUE TITLE
执行 python tools/process_data.py --config train.yaml 命令 

### ISSUE THREAD

**Issue by abchbx** [modelscope/data-juicer#425]
### Before Asking 在提问之前

- [X] I have read the [README](https://github.com/alibaba/data-juicer/blob/main/README.md) carefully. 我已经仔细阅读了 [README](https://github.com/alibaba/data-juicer/blob/main/README_ZH.md) 上的操作指引。

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking 先搜索，再提问

- [X] I have searched the Data-Juicer [issues](https://github.com/alibaba/data-juicer/issues) and found no similar questions. 我已经在 [issue列表](https://github.com/alibaba/data-juicer/issues) 中搜索但是没有发现类似的问题。

### Question

卡在处理数据downloading半天不动

### Additional 额外信息

![image](https://github.com/user-attachments/assets/a3847bf8-95af-4bd3-a048-bfc238c05159)
在执行 python tools/process_data.py --config train.yaml 命令以后，进度一直卡在这里，有什么办法可以加速吗？
2024-09-10 15:45:40 | INFO     | data_juicer.utils.model_utils:74 - Model [/root/.cache/data_juicer/models/lid.176.bin] not found. Downloading...

**Comment by drcege** [comment]
可以尝试从以下任一链接下载，放置到 `/root/.cache/data_juicer/models/` 目录下：
https://dail-wlcb.oss-cn-wulanchabu.aliyuncs.com/data_juicer/models/lid.176.bin
https://dl.fbaipublicfiles.com/fasttext/supervised-models/lid.176.bin
