### ISSUE TITLE
请问有没有提供 查看被算子筛选掉的数据 的功能

### ISSUE THREAD

**Issue by huangkaipeng4399** [modelscope/data-juicer#466]
### Before Asking 在提问之前

- [X] I have read the [README](https://github.com/alibaba/data-juicer/blob/main/README.md) carefully. 我已经仔细阅读了 [README](https://github.com/alibaba/data-juicer/blob/main/README_ZH.md) 上的操作指引。

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking 先搜索，再提问

- [X] I have searched the Data-Juicer [issues](https://github.com/alibaba/data-juicer/issues) and found no similar questions. 我已经在 [issue列表](https://github.com/alibaba/data-juicer/issues) 中搜索但是没有发现类似的问题。

### Question

想看看我们的数据集中筛掉的数据大概长什么样

**Comment by HYLcool** [comment]
嗨 @huangkaipeng4399 ，感谢你的关注与使用~

你可以在配置文件中设置open_tracer为true，然后设置合适的trace_num后，可以在每个OP结束后记录并在输出目录中导出OP处理前后发生变化的部分样本数据

可参考：
https://github.com/modelscope/data-juicer/blob/9e20e6a3ab05fd6265418210e74389b23296febe/configs/config_all.yaml#L20-L22

**Comment by huangkaipeng4399** [comment]
谢谢！

**Comment by monsieurzhang** [comment]
Hi, @HYLcool ,

请问参数 open_tracer 对 ray_bts_minhash_deduplicator 是无效吗？
我测试如果使用 document_minhash_deduplicator 可以生成 trace 目录，但是对 ray_xxx就没有 trace 目录

谢谢。
