### ISSUE TITLE
如何获取tool_quality_classifier模块中[chinese，code,gtp3]这3个模型的权重?

### ISSUE THREAD

**Issue by yaun248** [modelscope/data-juicer#467]
### Before Asking 在提问之前

- [X] I have read the [README](https://github.com/alibaba/data-juicer/blob/main/README.md) carefully. 我已经仔细阅读了 [README](https://github.com/alibaba/data-juicer/blob/main/README_ZH.md) 上的操作指引。

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking 先搜索，再提问

- [X] I have searched the Data-Juicer [issues](https://github.com/alibaba/data-juicer/issues) and found no similar questions. 我已经在 [issue列表](https://github.com/alibaba/data-juicer/issues) 中搜索但是没有发现类似的问题。

### Question

在使用tool_quality_classifier工具过程中如何获取到分类器模型的权重？我在/root/.cache/data_juicer/models/gpt3_quality_model这个路径下找了下存储大小只有4M，这应该不是一个模型的权重。

**Comment by HYLcool** [comment]
嗨 @yaun248 ，感谢你的关注与使用~

这三个模型均为spark的逻辑斯蒂回归分类器，你找到的那个路径中保存的就是模型的权重

**Comment by HYLcool** [comment]
Close this stale issue.
