### ISSUE TITLE
sharegpt format support

### ISSUE THREAD

**Issue by IvanDeng0** [modelscope/data-juicer#488]
### Before Asking 在提问之前

- [X] I have read the [README](https://github.com/alibaba/data-juicer/blob/main/README.md) carefully. 我已经仔细阅读了 [README](https://github.com/alibaba/data-juicer/blob/main/README_ZH.md) 上的操作指引。

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking 先搜索，再提问

- [X] I have searched the Data-Juicer [issues](https://github.com/alibaba/data-juicer/issues) and found no similar questions. 我已经在 [issue列表](https://github.com/alibaba/data-juicer/issues) 中搜索但是没有发现类似的问题。

### Question

my dataset is formed with sharegpt format, just like:
[
  {"conversations": [
    {"from": "user", "value": "..."},
    {"from": "gpt", "value": "..."},
    ]
  }
]

how to set the "text-keys"

**Comment by HYLcool** [comment]
Hi @IvanDeng0 , thanks for your suggestion!

As far as I know, the format of ShareGPT is the same as that of LLaVA. If so, we already support the llava-to-dj and dj-to-llava format conversion tools. You can find it in the LLaVA-like format section from [this document](https://github.com/modelscope/data-juicer/tree/main/tools/multimodal#llava-like) and check if it can meet your needs. If not, contact us and discuss your needs with us here.

If there are needs on SFT dataset format, please follow up. @drcege

**Comment by lostkevin** [comment]
For complex use, sharegpt-format  dataset can contain multiple images or videos like DJ format while LLaVA-format seems not. A more extensive script may be required for conversion. Reference: https://github.com/hiyouga/LLaMA-Factory/tree/main/data#multimodal-image-dataset-1

**Comment by yxdyc** [comment]
Thank you for your questions and suggestions! We have previously engaged in detailed design and discussions regarding the compatibility of the DJ schema with Modelscope-Swift and LLaMA-Factory, with the goal of supporting a wide range of post-tuning datasets and convenient training by ensuring compatibility with these two libraries.

An initial development effort has been made under PR #454 , where alignment for Modelscope-Swift's [query/response format](https://github.com/modelscope/ms-swift/blob/c2c0204d6b71e00c22116d632be5e86fe77879c5/docs/source_en/Customization/Custom-dataset.md#custom-dataset) has been implemented, which should be easily to extended for other formats like [Alpaca Format](https://github.com/hiyouga/LLaMA-Factory/blob/main/data/README.md#alpaca-format) (refer to the [AutoPreprocessor](https://github.com/modelscope/ms-swift/blob/bc3e78484c7b31f1a675a2e59f7260e2d6ecb21b/swift/llm/dataset/preprocessor/core.py#L446)). @HYLcool and I are working on more ready-to-use bidirectional conversion tools, firstly the [Sharegpt Format](https://github.com/hiyouga/LLaMA-Factory/blob/main/data/README.md#sharegpt-format).   

Welcome any discussions or PRs regarding this issue and next steps :)

Cc @cyruszhang: this might be useful for our AutoFormatter

**Comment by yxdyc** [comment]
Update: Initially implemented for sharegpt-format in #514, with a preliminary format specification. We are refactoring and will provide DJ's `DatasetLoaders` and `AutoFormatters` in the near future, in collaboration with @cyruszhang .
