### ISSUE TITLE
建议搞一个微信群，钉钉群，默认的钉钉群二维码已失效

### ISSUE THREAD

**Issue by baiyi-os** [modelscope/data-juicer#525]
### Search before continuing 先搜索，再继续

- [X] I have searched the Data-Juicer issues and found no similar feature requests. 我已经搜索了 Data-Juicer 的 issue 列表但是没有发现类似的功能需求。

### Description 描述

建议搞一个微信群，钉钉群，默认的钉钉群二维码已失效

### Are you willing to submit a PR for this feature? 您是否乐意为此功能提交一个 PR？

- [X] Yes I'd like to help by submitting a PR! 是的！我愿意提供帮助并提交一个PR！

**Comment by yxdyc** [comment]
Thanks for your feedback~ We have fixed the bad link in #513
